/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo Calvente
 */
public class VistaCDs extends javax.swing.JFrame {

    /**
     * Creates new form VistaLibros2
     */
    int xMouse, yMouse;
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    File foto = null;
    String indice;
    
    public void cargarDatosTabla() {
        //cargar los datos de la BBDD a la tabla con el jar rs2xml.jar
        try {
            //con = DriverManager.getConnection("jdbc:derby://localhost:1527/database2", "administrador", "administrador");
            con = DriverManager.getConnection("jdbc:derby:.\\database","administrador","administrador");
            st = con.createStatement();
            rs = st.executeQuery("select * from ADMINISTRADOR.CDS");
            //TablaLibrosArea.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableModel dfm = new DefaultTableModel();
            Tabla.setModel(dfm);
            dfm.setColumnIdentifiers((new Object[]{"NOMBRE", "CANTANTE", "NÚMERO DE CDS"}));
            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getString("NOMBRE"), rs.getString("CANTANTE"), rs.getInt("NUMCDS")});
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public String IDCDs(String nom) {
        String id = "-1";
        try {
            st = con.createStatement();
            rs = st.executeQuery("select ID from ADMINISTRADOR.CDS WHERE NOMBRE = '" + nom + "'");
            while (rs.next()) {
                id = Integer.toString(rs.getInt("ID"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return id;
    }
    
    public VistaCDs() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Base de Datos V1.0");
        setIconImage(new ImageIcon(getClass().getResource("/img/iconoapp.png")).getImage());
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(false);
        cargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Principal = new javax.swing.JPanel();
        Panel_Superior = new javax.swing.JPanel();
        Panel_Sup2 = new javax.swing.JPanel();
        Panel_X = new javax.swing.JPanel();
        XLabel = new javax.swing.JLabel();
        BBDDLabel = new javax.swing.JLabel();
        Panel_Inferior = new javax.swing.JPanel();
        CopyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Panel_BotonesYDemas = new javax.swing.JPanel();
        NombreLabel = new javax.swing.JLabel();
        NombreText = new javax.swing.JTextField();
        NombreSeparador = new javax.swing.JSeparator();
        CantanteLabel = new javax.swing.JLabel();
        CantanteText = new javax.swing.JTextField();
        CantanteSeparador = new javax.swing.JSeparator();
        NumCDsLabel = new javax.swing.JLabel();
        NumCDsBox = new javax.swing.JComboBox<>();
        PanelPortada = new javax.swing.JPanel();
        PortadaLabel = new javax.swing.JLabel();
        LinkText = new javax.swing.JTextField();
        LinkSeparador = new javax.swing.JSeparator();
        CaratulaLabel = new javax.swing.JLabel();
        CargarImagenBoton = new javax.swing.JButton();
        PanelBoton = new javax.swing.JPanel();
        BotonAnadir = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_Principal.setBackground(new java.awt.Color(204, 204, 204));

        Panel_Superior.setBackground(new java.awt.Color(255, 0, 0));

        Panel_Sup2.setBackground(new java.awt.Color(153, 153, 153));
        Panel_Sup2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_Sup2MouseDragged(evt);
            }
        });
        Panel_Sup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_Sup2MousePressed(evt);
            }
        });

        Panel_X.setBackground(new java.awt.Color(153, 153, 153));

        XLabel.setBackground(new java.awt.Color(204, 204, 204));
        XLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        XLabel.setForeground(new java.awt.Color(0, 0, 0));
        XLabel.setText("X");
        XLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_XLayout = new javax.swing.GroupLayout(Panel_X);
        Panel_X.setLayout(Panel_XLayout);
        Panel_XLayout.setHorizontalGroup(
            Panel_XLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_XLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(XLabel)
                .addContainerGap())
        );
        Panel_XLayout.setVerticalGroup(
            Panel_XLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_XLayout.createSequentialGroup()
                .addComponent(XLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_Sup2Layout = new javax.swing.GroupLayout(Panel_Sup2);
        Panel_Sup2.setLayout(Panel_Sup2Layout);
        Panel_Sup2Layout.setHorizontalGroup(
            Panel_Sup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Sup2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_Sup2Layout.setVerticalGroup(
            Panel_Sup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BBDDLabel.setBackground(new java.awt.Color(255, 0, 0));
        BBDDLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        BBDDLabel.setForeground(new java.awt.Color(255, 255, 255));
        BBDDLabel.setText("BASE DE DATOS");

        javax.swing.GroupLayout Panel_SuperiorLayout = new javax.swing.GroupLayout(Panel_Superior);
        Panel_Superior.setLayout(Panel_SuperiorLayout);
        Panel_SuperiorLayout.setHorizontalGroup(
            Panel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SuperiorLayout.createSequentialGroup()
                .addContainerGap(617, Short.MAX_VALUE)
                .addComponent(BBDDLabel)
                .addGap(537, 537, 537))
            .addComponent(Panel_Sup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_SuperiorLayout.setVerticalGroup(
            Panel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SuperiorLayout.createSequentialGroup()
                .addComponent(Panel_Sup2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BBDDLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Panel_Inferior.setBackground(new java.awt.Color(255, 0, 0));

        CopyLabel.setBackground(new java.awt.Color(255, 0, 0));
        CopyLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CopyLabel.setForeground(new java.awt.Color(255, 255, 255));
        CopyLabel.setText("© Pablo Jesús Calvente Ramírez");

        javax.swing.GroupLayout Panel_InferiorLayout = new javax.swing.GroupLayout(Panel_Inferior);
        Panel_Inferior.setLayout(Panel_InferiorLayout);
        Panel_InferiorLayout.setHorizontalGroup(
            Panel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CopyLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_InferiorLayout.setVerticalGroup(
            Panel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CopyLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        Tabla.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 0, 0));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantante", "Numero CDs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Panel_BotonesYDemas.setBackground(new java.awt.Color(204, 204, 204));

        NombreLabel.setBackground(new java.awt.Color(204, 204, 204));
        NombreLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        NombreLabel.setText("Nombre:");

        NombreText.setBackground(new java.awt.Color(204, 204, 204));
        NombreText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreText.setForeground(new java.awt.Color(0, 0, 0));
        NombreText.setBorder(null);

        CantanteLabel.setBackground(new java.awt.Color(204, 204, 204));
        CantanteLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CantanteLabel.setForeground(new java.awt.Color(0, 0, 0));
        CantanteLabel.setText("Cantante:");

        CantanteText.setBackground(new java.awt.Color(204, 204, 204));
        CantanteText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CantanteText.setForeground(new java.awt.Color(0, 0, 0));
        CantanteText.setBorder(null);

        NumCDsLabel.setBackground(new java.awt.Color(204, 204, 204));
        NumCDsLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NumCDsLabel.setForeground(new java.awt.Color(0, 0, 0));
        NumCDsLabel.setText("Número de CDs:");

        NumCDsBox.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NumCDsBox.setForeground(new java.awt.Color(0, 0, 0));
        NumCDsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"}));

        PanelPortada.setBackground(new java.awt.Color(204, 204, 204));

        PortadaLabel.setBackground(new java.awt.Color(204, 204, 204));
        PortadaLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PortadaLabel.setForeground(new java.awt.Color(0, 0, 0));
        PortadaLabel.setText("Portada:");

        LinkText.setEditable(false);
        LinkText.setBackground(new java.awt.Color(204, 204, 204));
        LinkText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        LinkText.setForeground(new java.awt.Color(0, 0, 0));
        LinkText.setBorder(null);

        CaratulaLabel.setBackground(new java.awt.Color(204, 204, 204));
        CaratulaLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CaratulaLabel.setForeground(new java.awt.Color(0, 0, 0));
        CaratulaLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CargarImagenBoton.setBackground(new java.awt.Color(255, 255, 255));
        CargarImagenBoton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CargarImagenBoton.setForeground(new java.awt.Color(0, 0, 0));
        CargarImagenBoton.setText("Cargar Imagen");
        CargarImagenBoton.setToolTipText("");
        CargarImagenBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarImagenBoton.setMaximumSize(new java.awt.Dimension(99, 23));
        CargarImagenBoton.setMinimumSize(new java.awt.Dimension(99, 23));
        CargarImagenBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarImagenBotonMouseClicked(evt);
            }
        });
        CargarImagenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarImagenBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPortadaLayout = new javax.swing.GroupLayout(PanelPortada);
        PanelPortada.setLayout(PanelPortadaLayout);
        PanelPortadaLayout.setHorizontalGroup(
            PanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortadaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkSeparador)
                    .addComponent(LinkText)))
            .addGroup(PanelPortadaLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(PanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CaratulaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargarImagenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPortadaLayout.setVerticalGroup(
            PanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortadaLabel)
                    .addComponent(LinkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaratulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CargarImagenBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelBoton.setBackground(new java.awt.Color(204, 204, 204));

        BotonAnadir.setBackground(new java.awt.Color(255, 255, 255));
        BotonAnadir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonAnadir.setForeground(new java.awt.Color(0, 0, 0));
        BotonAnadir.setText("Añadir");
        BotonAnadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAnadirMouseClicked(evt);
            }
        });

        BotonEditar.setBackground(new java.awt.Color(255, 255, 255));
        BotonEditar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonEditar.setForeground(new java.awt.Color(0, 0, 0));
        BotonEditar.setText("Editar");
        BotonEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEditarMouseClicked(evt);
            }
        });
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseClicked(evt);
            }
        });

        BotonInicio.setBackground(new java.awt.Color(255, 255, 255));
        BotonInicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonInicio.setForeground(new java.awt.Color(0, 0, 0));
        BotonInicio.setText("Inicio");
        BotonInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonLayout = new javax.swing.GroupLayout(PanelBoton);
        PanelBoton.setLayout(PanelBotonLayout);
        PanelBotonLayout.setHorizontalGroup(
            PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(BotonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBotonLayout.setVerticalGroup(
            PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout Panel_BotonesYDemasLayout = new javax.swing.GroupLayout(Panel_BotonesYDemas);
        Panel_BotonesYDemas.setLayout(Panel_BotonesYDemasLayout);
        Panel_BotonesYDemasLayout.setHorizontalGroup(
            Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                        .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                                .addComponent(NombreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreSeparador)
                                    .addComponent(NombreText)))
                            .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                                .addComponent(CantanteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantanteSeparador)
                                    .addComponent(CantanteText)))
                            .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                                .addComponent(NumCDsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumCDsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        Panel_BotonesYDemasLayout.setVerticalGroup(
            Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BotonesYDemasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel)
                    .addComponent(NombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantanteLabel)
                    .addComponent(CantanteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantanteSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_BotonesYDemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCDsLabel)
                    .addComponent(NumCDsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_Inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_BotonesYDemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addComponent(Panel_Superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Panel_BotonesYDemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_XLabelMouseClicked

    private void XLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XLabelMouseEntered
        // TODO add your handling code here:
        Panel_X.setBackground(Color.RED);
        XLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_XLabelMouseEntered

    private void XLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XLabelMouseExited
        // TODO add your handling code here:
        Panel_X.setBackground(Color.GRAY);
        XLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_XLabelMouseExited

    private void Panel_Sup2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Sup2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel_Sup2MouseDragged

    private void Panel_Sup2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Sup2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Panel_Sup2MousePressed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void CargarImagenBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarImagenBotonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CargarImagenBotonMouseClicked

    private void CargarImagenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarImagenBotonActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setMultiSelectionEnabled(true);
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        filechooser.setFileFilter(filtro);
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("*.png", "png");
        filechooser.setFileFilter(filtro2);
        int select = filechooser.showOpenDialog(Panel_Superior);
        if (select == JFileChooser.APPROVE_OPTION) {
            foto = filechooser.getSelectedFile();
            LinkText.setText(foto.getAbsolutePath());
            ImageIcon original = new ImageIcon(foto.getAbsolutePath());
            Image img = original.getImage();
            Image escalada = img.getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            ImageIcon fotoEscalada = new ImageIcon(escalada);
            CaratulaLabel.setIcon(fotoEscalada);
        }
    }//GEN-LAST:event_CargarImagenBotonActionPerformed

    private void BotonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseClicked
        // TODO add your handling code here:
        VistaPrincipal a = new VistaPrincipal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonInicioMouseClicked

    private void BotonAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAnadirMouseClicked
        // TODO add your handling code here:
        try {
            //con = DriverManager.getConnection("jdbc:derby://localhost:1527/database2", "administrador", "administrador");
            con = DriverManager.getConnection("jdbc:derby:.\\database","administrador","administrador");
            PreparedStatement add = con.prepareStatement("insert into ADMINISTRADOR.CDS (NOMBRE, CANTANTE, NUMCDS, IMAGEN) values(?,?,?,?)");

            add.setString(1, NombreText.getText());
            add.setString(2, CantanteText.getText());
            add.setString(3, NumCDsBox.getSelectedItem().toString());
            
            FileInputStream fi = new FileInputStream(foto);
            add.setBlob(4, fi, foto.length());

            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Se ha añadido correctamente el CD.");
            con.close();
            cargarDatosTabla();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VistaLibros.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(this, "Error añade foto");
        }
    }//GEN-LAST:event_BotonAnadirMouseClicked

    private void BotonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseClicked
        // TODO add your handling code here:
        try {
            //con = DriverManager.getConnection("jdbc:derby://localhost:1527/database2", "administrador", "administrador");
            con = DriverManager.getConnection("jdbc:derby:.\\database","administrador","administrador");

            String Query = "delete from ADMINISTRADOR.CDS where ID=" + indice;
            Statement add = con.createStatement();
            add.executeUpdate(Query);
            cargarDatosTabla();
            con.close();
            JOptionPane.showMessageDialog(this, "CD Borrado");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonEliminarMouseClicked

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        int ind = Tabla.getSelectedRow();

        NombreText.setText(modelo.getValueAt(ind, 0).toString());
        CantanteText.setText(modelo.getValueAt(ind, 1).toString());
        NumCDsBox.setSelectedItem(modelo.getValueAt(ind, 2).toString()); 
        try {
            String nombre = NombreText.getText();
            //con = DriverManager.getConnection("jdbc:derby://localhost:1527/database2", "administrador", "administrador");
            con = DriverManager.getConnection("jdbc:derby:.\\database","administrador","administrador");
            st = con.createStatement();
            indice = IDCDs(nombre);
            rs = st.executeQuery("SELECT IMAGEN FROM ADMINISTRADOR.CDS where ID = " + indice);
            byte[] image = null;
            while (rs.next()) {
                Blob blob = rs.getBlob("IMAGEN");
                Image img2 = javax.imageio.ImageIO.read(blob.getBinaryStream());
                image = blob.getBytes(1, (int) blob.length());
                ImageIcon imagen = new ImageIcon(img2);
                ImageIcon fotoEscalada = new ImageIcon(imagen.getImage().getScaledInstance(CaratulaLabel.getWidth(), CaratulaLabel.getHeight(), Image.SCALE_DEFAULT));
                CaratulaLabel.setIcon(fotoEscalada);
                LinkText.setText("");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(VistaLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void BotonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEditarMouseClicked
        // TODO add your handling code here:
        try{
                //con = DriverManager.getConnection("jdbc:derby://localhost:1527/database2","administrador","administrador");
                con = DriverManager.getConnection("jdbc:derby:.\\database","administrador","administrador");
                String updateQuery = "update ADMINISTRADOR.CDS set NOMBRE='"+NombreText.getText()+"',CANTANTE='"+CantanteText.getText()+"',NUMCDS="+NumCDsBox.getSelectedItem(); 
                updateQuery += " where ID="+indice;
                java.sql.Statement add = con.createStatement();
                add.executeUpdate(updateQuery);
                JOptionPane.showMessageDialog(this, "Actualización del CD ha sido llevada a cabo.");
                con.close();
                cargarDatosTabla();
            }catch(SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_BotonEditarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCDs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BBDDLabel;
    private javax.swing.JButton BotonAnadir;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CantanteLabel;
    private javax.swing.JSeparator CantanteSeparador;
    private javax.swing.JTextField CantanteText;
    private javax.swing.JLabel CaratulaLabel;
    private javax.swing.JButton CargarImagenBoton;
    private javax.swing.JLabel CopyLabel;
    private javax.swing.JSeparator LinkSeparador;
    private javax.swing.JTextField LinkText;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JSeparator NombreSeparador;
    private javax.swing.JTextField NombreText;
    private javax.swing.JComboBox<String> NumCDsBox;
    private javax.swing.JLabel NumCDsLabel;
    private javax.swing.JPanel PanelBoton;
    private javax.swing.JPanel PanelPortada;
    private javax.swing.JPanel Panel_BotonesYDemas;
    private javax.swing.JPanel Panel_Inferior;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_Sup2;
    private javax.swing.JPanel Panel_Superior;
    private javax.swing.JPanel Panel_X;
    private javax.swing.JLabel PortadaLabel;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel XLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
